### ISSUE TITLE
DevCon4 Presentation - FISSION Codes & Translate

### ISSUE THREAD

**Issue by bmann** [spadebuilders/community#12]
Brooke is presenting at DevCon4 on FISSION Codes & Translate.

**Comment by expede** [comment]
- [x] Link to presentation
- [x] Video

**Comment by expede** [comment]
https://slideslive.ch/38911936/erc1066-better-ux-dx-in-just-one-byte

**Comment by expede** [comment]
@bmann any preference where the slides themselves get hosted? Slideshare? I feel like you mentioned another option recently.

**Comment by bmann** [comment]
@expede I’ve always just used SpeakerDeck but it’s PDF only and is pretty basic. There are a bunch of new options like Slides.com. 

Post original for me to our Discord and I can take care of it.

**Comment by expede** [comment]
https://speakerdeck.com/expede/the-fission-suite-one-byte-of-context-devcon-iv
