### ISSUE TITLE
Community Call - Dec 4 - FISSION Token Codes Review

### ISSUE THREAD

**Issue by bmann** [spadebuilders/community#13]
Community Call tentatively scheduled for Dec 4, 8:30am PST.
* Community Calendar
* Zoom Video Link https://zoom.us/j/849295035
* [Discord chat #lobby](https://discord.gg/daDMAjE)

Please add topics and questions for discussion below, and use reactions to indicate which ones you like.

**Comment by bmann** [comment]
@0age is suggesting some token transfer related codes:

> I’d like to propose a group of status codes specifically tailored to token transfers in the 0x5* range (as a pretty significant proportion of transactions deal specifically in that department :smile:). 5 is unused so far, and looks a bit like $ so seems a natural fit to me.

Discussion on [EthMagicians](https://ethereum-magicians.org/t/erc-1066-ethereum-status-codes-esc/283/21)

**Comment by bmann** [comment]
Agenda item: Submitting 1066 to Ethereum Classic ECIP #11 
Talking to @pyskell about this. Can invite Ethereum Classic community members to join call and ask questions.

**Comment by pyskell** [comment]
Happy to join the call. Will share this link with others.

Also cc @YazzyYaz

**Comment by bmann** [comment]
Rescheduled this to Dec 4th. Had a productive chat with EthClassic about this, will aim to get submitted to ECIP repo #11 before the call.

Reached out to @0age on EthMagicians to see about availability on Dec 4th.

**Comment by bmann** [comment]
Confirming @0age will be on call

Submitted to EthClassic https://github.com/ethereumproject/ECIPs/pull/98 -- anyone from EthClassic is happy to dial in and we can talk more generally about Status Codes and Translate and so on.

Zoom link! https://zoom.us/j/849295035

See you all tomorrow.

**Comment by bmann** [comment]
Notes here https://hackmd.io/Rhf176qDRD2szn4ouojfWg

Good discussion with @0age on refactoring his TPL to use updated codes, would love more feedback on that.

We're going to look at some sample contracts to deploy / work on for re-use -- notes at end of HackMD doc where we brainstormed a bit.

And, translate roll out #22

**Comment by expede** [comment]
@bmann I'm guessing that this is closable, да?
