### ISSUE TITLE
Process of rolling out EIP615 Static Jumps and other EVM opcode additions

### ISSUE THREAD

**Issue by bmann** [spadebuilders/community#18]
Write up a high level set of steps to help explain how new EVM opcodes get rolled out. Focus on [EIP615 Static Jumps](https://github.com/ethereum/EIPs/issues/615).

**Comment by bmann** [comment]
I went ahead and did a high level write up here https://hackmd.io/WmnAxhCsS1yd50hj9Ai7eg

**Comment by expede** [comment]
* https://ethereum-magicians.org/t/eip-615-subroutines-and-static-jumps-for-the-evm/2728/70
* https://github.com/ethereum/EIPs/issues/615

**Comment by bmann** [comment]
This was a process ticket. I’m going to close it, as the summary seems to be - propose a PR against the Hardfork meta.
