### ISSUE TITLE
Plan an All EVM Call to gather interest

### ISSUE THREAD

**Issue by bmann** [spadebuilders/community#20]
We had ETC Cooperative on the Community Call #14. There are many other blockchains that run EVM or EVM compatible smart contracts.

Can we coordinate and collaborate more broadly among all these chains to get a better VM for everyone?

Making a list of EVM compatible chains / clients and who to contact is likely the first step. Will create a markdown file for that in this repo.

**Comment by bmann** [comment]
For now, before creating a markdown file, feel free to add EVM compatible chains in the comments here.

**Comment by bmann** [comment]
I had the Ethereum Lists org pointed out to me. I guess I will create a repo and request to transfer it there. 

https://github.com/ethereum-lists

**Comment by expede** [comment]
@bmann does this now fall under RUN EVM?

**Comment by bmann** [comment]
We made a whole conference instead! https://runevm.com
